CREATE TABLE IF NOT EXISTS `#__appsconda_webviewmenus` (
  `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  `menu1show` varchar(6) NOT NULL,
  `menu1label` varchar(50) NOT NULL,
  `menu1color` varchar(10) NOT NULL,
  `menu1icon` varchar(255) NOT NULL,
  `menu1content` text NOT NULL,
  `menu2show` varchar(6) NOT NULL,
  `menu2label` varchar(50) NOT NULL,
  `menu2color` varchar(10) NOT NULL,
  `menu2icon` varchar(255) NOT NULL,
  `menu2content` text NOT NULL,
  `menu3show` varchar(6) NOT NULL,
  `menu3label` varchar(50) NOT NULL,
  `menu3color` varchar(10) NOT NULL,
  `menu3icon` varchar(255) NOT NULL,
  `menu3content` text NOT NULL,
  `menu4show` varchar(6) NOT NULL,
  `menu4label` varchar(50) NOT NULL,
  `menu4color` varchar(10) NOT NULL,
  `menu4icon` varchar(255) NOT NULL,
  `menu4content` text NOT NULL,
  `menu5show` varchar(6) NOT NULL,
  `menu5label` varchar(50) NOT NULL,
  `menu5color` varchar(10) NOT NULL,
  `menu5icon` varchar(255) NOT NULL,
  `menu5content` text NOT NULL,
  `menu6show` varchar(6) NOT NULL,
  `menu6label` varchar(50) NOT NULL,
  `menu6color` varchar(10) NOT NULL,
  `menu6icon` varchar(255) NOT NULL,
  `menu6content` text NOT NULL,
  `menu7show` varchar(6) NOT NULL,
  `menu7label` varchar(50) NOT NULL,
  `menu7color` varchar(10) NOT NULL,
  `menu7icon` varchar(255) NOT NULL,
  `menu7content` text NOT NULL,
  `menu8show` varchar(6) NOT NULL,
  `menu8label` varchar(50) NOT NULL,
  `menu8color` varchar(10) NOT NULL,
  `menu8icon` varchar(255) NOT NULL,
  `menu8content` text NOT NULL,
  `menu9show` varchar(6) NOT NULL,
  `menu9label` varchar(50) NOT NULL,
  `menu9color` varchar(10) NOT NULL,
  `menu9icon` varchar(255) NOT NULL,
  `menu9content` text NOT NULL,
  `menu10show` varchar(6) NOT NULL,
  `menu10label` varchar(50) NOT NULL,
  `menu10color` varchar(10) NOT NULL,
  `menu10icon` varchar(255) NOT NULL,
  `menu10content` text NOT NULL,
  `menu11show` varchar(6) NOT NULL,
  `menu11label` varchar(50) NOT NULL,
  `menu11color` varchar(10) NOT NULL,
  `menu11icon` varchar(255) NOT NULL,
  `menu11content` text NOT NULL,
  `menu12show` varchar(6) NOT NULL,
  `menu12label` varchar(50) NOT NULL,
  `menu12color` varchar(10) NOT NULL,
  `menu12icon` varchar(255) NOT NULL,
  `menu12content` text NOT NULL,
  `menu13show` varchar(6) NOT NULL,
  `menu13label` varchar(50) NOT NULL,
  `menu13color` varchar(10) NOT NULL,
  `menu13icon` varchar(255) NOT NULL,
  `menu13content` text NOT NULL,
  `menu14show` varchar(6) NOT NULL,
  `menu14label` varchar(50) NOT NULL,
  `menu14color` varchar(10) NOT NULL,
  `menu14icon` varchar(255) NOT NULL,
  `menu14content` text NOT NULL, 
  `menu15show` varchar(6) NOT NULL,
  `menu15label` varchar(50) NOT NULL,
  `menu15color` varchar(10) NOT NULL,
  `menu15icon` varchar(255) NOT NULL,
  `menu15content` text NOT NULL,
  `created_by` int(11) NOT NULL,
  `state` int(11) NOT NULL DEFAULT 1,
  `ordering` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB COMMENT="" DEFAULT COLLATE=utf8_general_ci;

INSERT IGNORE INTO `#__appsconda_webviewmenus` (`id`, `menu1show`, `menu1label`, `menu1color`, `menu1icon`, `menu1content`, `menu2show`, `menu2label`, `menu2color`, `menu2icon`, `menu2content`, `menu3show`, `menu3label`, `menu3color`, `menu3icon`, `menu3content`, `menu4show`, `menu4label`, `menu4color`, `menu4icon`, `menu4content`, `menu5show`, `menu5label`, `menu5color`, `menu5icon`, `menu5content`, `menu6show`, `menu6label`, `menu6color`, `menu6icon`, `menu6content`, `menu7show`, `menu7label`, `menu7color`, `menu7icon`, `menu7content`, `menu8show`, `menu8label`, `menu8color`, `menu8icon`, `menu8content`, `menu9show`, `menu9label`, `menu9color`, `menu9icon`, `menu9content`, `menu10show`, `menu10label`, `menu10color`, `menu10icon`, `menu10content`, `menu11show`, `menu11label`, `menu11color`, `menu11icon`, `menu11content`, `menu12show`, `menu12label`, `menu12color`, `menu12icon`, `menu12content`, `menu13show`, `menu13label`, `menu13color`, `menu13icon`, `menu13content`, `menu14show`, `menu14label`, `menu14color`, `menu14icon`, `menu14content`, `menu15show`, `menu15label`, `menu15color`, `menu15icon`, `menu15content`, `created_by`, `state`, `ordering`) VALUES
(1, 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 'false', '', '', '', '', 0, 1, 0);
